spring:
  application:
    name: bokati-cowork

  profiles:
    active: dev

  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics