package com.sni.bokaticowork.features.subscription.subscription.enums;

public enum SubscriptionEventType {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_SUSPENDED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED,
    PLAN_CHANGED,
    ENTITLEMENTS_GRANTED,
    BILLING_SCHEDULED,
    DOCUMENTS_PENDING,
    GRACE_PERIOD_ENTERED,
    GRACE_PERIOD_EXITED,
    TERMINATION_REQUESTED,
    TERMINATION_ACCEPTED,
    TERMINATION_RETRACTED,
    COMMITMENT_SET,
    FREEZE_STARTED,
    DIRECT_DEBIT_SUCCEEDED,
    DIRECT_DEBIT_FAILED,
    DATES_ALIGNED
}
