package com.sni.bokaticowork.features.booking.enums;

public enum BookingEventType {
    BOOKING_CREATED,
    BOOKING_HOLD_CREATED,
    BOOKING_HOLD_EXPIRED,
    BOOKING_CONFIRMED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_STARTED,
    BOOKING_CHECKED_IN,
    BOOKING_CHECKED_OUT,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    BOOKING_NO_SHOW,
    RESOURCE_RESERVED,
    RESOURCE_RELEASED,
    ENTITLEMENT_RESERVED,
    ENTITLEMENT_CONSUMED,
    ENTITLEMENT_RELEASED,
    USAGE_RECORDED,
    EMAIL_QUEUED,
    EMAIL_SENT,
    EMAIL_FAILED,
    REPAIR_APPLIED,
    QUOTA_OVERRIDE_APPLIED
}
