ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS profile_picture_url VARCHAR(500);
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS job_title VARCHAR(120);
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS company_role VARCHAR(120);
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS city VARCHAR(120);
ALTER TABLE member_profile ADD COLUMN IF NOT EXISTS country VARCHAR(120);
