-- Seed world countries with phone codes and default currencies
-- Currency IDs start at 1100; country IDs start at 2100
-- ON CONFLICT (country_code) DO NOTHING ensures idempotence

-- ── Currencies ───────────────────────────────────────────────────────────────
INSERT INTO currency (id, currency_code, currency_name, created_at, updated_at) VALUES
  (1100, 'EUR', 'Euro',                        now(), now()),
  (1101, 'USD', 'US Dollar',                   now(), now()),
  (1102, 'XOF', 'West African CFA Franc',      now(), now()),
  (1103, 'GBP', 'British Pound Sterling',      now(), now()),
  (1104, 'NGN', 'Nigerian Naira',              now(), now()),
  (1105, 'KES', 'Kenyan Shilling',             now(), now()),
  (1106, 'GHS', 'Ghanaian Cedi',               now(), now()),
  (1107, 'ZAR', 'South African Rand',          now(), now()),
  (1108, 'MAD', 'Moroccan Dirham',             now(), now()),
  (1109, 'EGP', 'Egyptian Pound',              now(), now()),
  (1110, 'ETB', 'Ethiopian Birr',              now(), now()),
  (1111, 'TZS', 'Tanzanian Shilling',          now(), now()),
  (1112, 'UGX', 'Ugandan Shilling',            now(), now()),
  (1113, 'CDF', 'Congolese Franc',             now(), now()),
  (1114, 'AOA', 'Angolan Kwanza',              now(), now()),
  (1115, 'RWF', 'Rwandan Franc',               now(), now()),
  (1116, 'BIF', 'Burundian Franc',             now(), now()),
  (1117, 'MZN', 'Mozambican Metical',          now(), now()),
  (1118, 'ZMW', 'Zambian Kwacha',              now(), now()),
  (1119, 'MWK', 'Malawian Kwacha',             now(), now()),
  (1120, 'BWP', 'Botswana Pula',               now(), now()),
  (1121, 'NAD', 'Namibian Dollar',             now(), now()),
  (1122, 'MUR', 'Mauritian Rupee',             now(), now()),
  (1123, 'SCR', 'Seychellois Rupee',           now(), now()),
  (1124, 'DJF', 'Djiboutian Franc',            now(), now()),
  (1125, 'ERN', 'Eritrean Nakfa',              now(), now()),
  (1126, 'SDG', 'Sudanese Pound',              now(), now()),
  (1127, 'SOS', 'Somali Shilling',             now(), now()),
  (1128, 'GMD', 'Gambian Dalasi',              now(), now()),
  (1129, 'SLL', 'Sierra Leonean Leone',        now(), now()),
  (1130, 'LRD', 'Liberian Dollar',             now(), now()),
  (1131, 'CVE', 'Cape Verdean Escudo',         now(), now()),
  (1132, 'STN', 'São Tomé and Príncipe Dobra', now(), now()),
  (1133, 'MRU', 'Mauritanian Ouguiya',         now(), now()),
  (1134, 'DZD', 'Algerian Dinar',              now(), now()),
  (1135, 'TND', 'Tunisian Dinar',              now(), now()),
  (1136, 'LYD', 'Libyan Dinar',                now(), now()),
  (1137, 'GNF', 'Guinean Franc',               now(), now()),
  (1138, 'MGA', 'Malagasy Ariary',             now(), now()),
  (1139, 'KMF', 'Comorian Franc',              now(), now()),
  (1140, 'SZL', 'Swazi Lilangeni',             now(), now()),
  (1141, 'LSL', 'Lesotho Loti',                now(), now()),
  (1142, 'JPY', 'Japanese Yen',                now(), now()),
  (1143, 'CNY', 'Chinese Yuan',                now(), now()),
  (1144, 'INR', 'Indian Rupee',                now(), now()),
  (1145, 'BRL', 'Brazilian Real',              now(), now()),
  (1146, 'CAD', 'Canadian Dollar',             now(), now()),
  (1147, 'CHF', 'Swiss Franc',                 now(), now()),
  (1148, 'AUD', 'Australian Dollar',           now(), now()),
  (1149, 'MXN', 'Mexican Peso',                now(), now()),
  (1150, 'ARS', 'Argentine Peso',              now(), now()),
  (1151, 'CLP', 'Chilean Peso',                now(), now()),
  (1152, 'COP', 'Colombian Peso',              now(), now()),
  (1153, 'PEN', 'Peruvian Sol',                now(), now()),
  (1154, 'SAR', 'Saudi Riyal',                 now(), now()),
  (1155, 'AED', 'UAE Dirham',                  now(), now()),
  (1156, 'TRY', 'Turkish Lira',                now(), now()),
  (1157, 'RUB', 'Russian Ruble',               now(), now()),
  (1158, 'KRW', 'South Korean Won',            now(), now()),
  (1159, 'SGD', 'Singapore Dollar',            now(), now()),
  (1160, 'MYR', 'Malaysian Ringgit',           now(), now()),
  (1161, 'THB', 'Thai Baht',                   now(), now()),
  (1162, 'VND', 'Vietnamese Dong',             now(), now()),
  (1163, 'IDR', 'Indonesian Rupiah',           now(), now()),
  (1164, 'PKR', 'Pakistani Rupee',             now(), now()),
  (1165, 'BDT', 'Bangladeshi Taka',            now(), now()),
  (1166, 'NOK', 'Norwegian Krone',             now(), now()),
  (1167, 'SEK', 'Swedish Krona',               now(), now()),
  (1168, 'DKK', 'Danish Krone',                now(), now()),
  (1169, 'PLN', 'Polish Zloty',                now(), now()),
  (1170, 'UAH', 'Ukrainian Hryvnia',           now(), now()),
  (1171, 'ILS', 'Israeli New Shekel',          now(), now()),
  (1172, 'QAR', 'Qatari Riyal',                now(), now()),
  (1173, 'KWD', 'Kuwaiti Dinar',               now(), now()),
  (1174, 'BHD', 'Bahraini Dinar',              now(), now()),
  (1175, 'OMR', 'Omani Rial',                  now(), now()),
  (1176, 'JOD', 'Jordanian Dinar',             now(), now()),
  (1177, 'LBP', 'Lebanese Pound',              now(), now()),
  (1178, 'IRR', 'Iranian Rial',                now(), now()),
  (1179, 'IQD', 'Iraqi Dinar',                 now(), now()),
  (1180, 'NPR', 'Nepalese Rupee',              now(), now()),
  (1181, 'LKR', 'Sri Lankan Rupee',            now(), now()),
  (1182, 'PHP', 'Philippine Peso',             now(), now()),
  (1183, 'NZD', 'New Zealand Dollar',          now(), now()),
  (1184, 'HTG', 'Haitian Gourde',              now(), now()),
  (1185, 'GTQ', 'Guatemalan Quetzal',          now(), now()),
  (1186, 'CRC', 'Costa Rican Colón',           now(), now()),
  (1187, 'DOP', 'Dominican Peso',              now(), now()),
  (1188, 'JMD', 'Jamaican Dollar',             now(), now()),
  (1189, 'TTD', 'Trinidad and Tobago Dollar',  now(), now()),
  (1190, 'ZWL', 'Zimbabwean Dollar',           now(), now())
ON CONFLICT DO NOTHING;

-- ── Countries ─────────────────────────────────────────────────────────────────
INSERT INTO country (id, name, country_code, default_currency_code, phone_code, is_ohada_member, deleted, created_at, updated_at) VALUES
-- OHADA Africa (XAF zone) — Congo (CG) already seeded in V11
  (2100, 'République Démocratique du Congo', 'CD', 1113, '+243', true,  false, now(), now()),
  (2101, 'Cameroun',                         'CM', 1001, '+237', true,  false, now(), now()),
  (2102, 'Gabon',                            'GA', 1001, '+241', true,  false, now(), now()),
  (2103, 'République Centrafricaine',        'CF', 1001, '+236', true,  false, now(), now()),
  (2104, 'Tchad',                            'TD', 1001, '+235', true,  false, now(), now()),
  (2105, 'Guinée Équatoriale',              'GQ', 1001, '+240', true,  false, now(), now()),
-- OHADA Africa (XOF zone)
  (2106, 'Sénégal',                         'SN', 1102, '+221', true,  false, now(), now()),
  (2107, 'Côte d''Ivoire',                  'CI', 1102, '+225', true,  false, now(), now()),
  (2108, 'Mali',                             'ML', 1102, '+223', true,  false, now(), now()),
  (2109, 'Burkina Faso',                     'BF', 1102, '+226', true,  false, now(), now()),
  (2110, 'Niger',                            'NE', 1102, '+227', true,  false, now(), now()),
  (2111, 'Bénin',                            'BJ', 1102, '+229', true,  false, now(), now()),
  (2112, 'Togo',                             'TG', 1102, '+228', true,  false, now(), now()),
  (2113, 'Guinée-Bissau',                   'GW', 1102, '+245', true,  false, now(), now()),
-- OHADA others
  (2114, 'Guinée',                           'GN', 1137, '+224', true,  false, now(), now()),
  (2115, 'Comores',                          'KM', 1139, '+269', true,  false, now(), now()),
-- Other Africa
  (2116, 'Nigeria',                          'NG', 1104, '+234', false, false, now(), now()),
  (2117, 'Kenya',                            'KE', 1105, '+254', false, false, now(), now()),
  (2118, 'Afrique du Sud',                  'ZA', 1107, '+27',  false, false, now(), now()),
  (2119, 'Éthiopie',                        'ET', 1110, '+251', false, false, now(), now()),
  (2120, 'Tanzanie',                         'TZ', 1111, '+255', false, false, now(), now()),
  (2121, 'Ouganda',                          'UG', 1112, '+256', false, false, now(), now()),
  (2122, 'Rwanda',                           'RW', 1115, '+250', false, false, now(), now()),
  (2123, 'Burundi',                          'BI', 1116, '+257', false, false, now(), now()),
  (2124, 'Angola',                           'AO', 1114, '+244', false, false, now(), now()),
  (2125, 'Mozambique',                       'MZ', 1117, '+258', false, false, now(), now()),
  (2126, 'Zambie',                           'ZM', 1118, '+260', false, false, now(), now()),
  (2127, 'Malawi',                           'MW', 1119, '+265', false, false, now(), now()),
  (2128, 'Zimbabwe',                         'ZW', 1190, '+263', false, false, now(), now()),
  (2129, 'Botswana',                         'BW', 1120, '+267', false, false, now(), now()),
  (2130, 'Namibie',                          'NA', 1121, '+264', false, false, now(), now()),
  (2131, 'Eswatini',                         'SZ', 1140, '+268', false, false, now(), now()),
  (2132, 'Lesotho',                          'LS', 1141, '+266', false, false, now(), now()),
  (2133, 'Madagascar',                       'MG', 1138, '+261', false, false, now(), now()),
  (2134, 'Maurice',                          'MU', 1122, '+230', false, false, now(), now()),
  (2135, 'Seychelles',                       'SC', 1123, '+248', false, false, now(), now()),
  (2136, 'Djibouti',                         'DJ', 1124, '+253', false, false, now(), now()),
  (2137, 'Érythrée',                        'ER', 1125, '+291', false, false, now(), now()),
  (2138, 'Somalie',                          'SO', 1127, '+252', false, false, now(), now()),
  (2139, 'Soudan',                           'SD', 1126, '+249', false, false, now(), now()),
  (2140, 'Soudan du Sud',                   'SS', 1101, '+211', false, false, now(), now()),
  (2141, 'Gambie',                           'GM', 1128, '+220', false, false, now(), now()),
  (2142, 'Sierra Leone',                     'SL', 1129, '+232', false, false, now(), now()),
  (2143, 'Libéria',                         'LR', 1130, '+231', false, false, now(), now()),
  (2144, 'Ghana',                            'GH', 1106, '+233', false, false, now(), now()),
  (2145, 'Cap-Vert',                        'CV', 1131, '+238', false, false, now(), now()),
  (2146, 'São Tomé-et-Príncipe',           'ST', 1132, '+239', false, false, now(), now()),
  (2147, 'Mauritanie',                       'MR', 1133, '+222', false, false, now(), now()),
  (2148, 'Maroc',                            'MA', 1108, '+212', false, false, now(), now()),
  (2149, 'Algérie',                         'DZ', 1134, '+213', false, false, now(), now()),
  (2150, 'Tunisie',                          'TN', 1135, '+216', false, false, now(), now()),
  (2151, 'Libye',                            'LY', 1136, '+218', false, false, now(), now()),
  (2152, 'Égypte',                          'EG', 1109, '+20',  false, false, now(), now()),
-- Europe
  (2200, 'France',                           'FR', 1100, '+33',  false, false, now(), now()),
  (2201, 'Belgique',                         'BE', 1100, '+32',  false, false, now(), now()),
  (2202, 'Suisse',                           'CH', 1147, '+41',  false, false, now(), now()),
  (2203, 'Allemagne',                        'DE', 1100, '+49',  false, false, now(), now()),
  (2204, 'Italie',                           'IT', 1100, '+39',  false, false, now(), now()),
  (2205, 'Espagne',                          'ES', 1100, '+34',  false, false, now(), now()),
  (2206, 'Portugal',                         'PT', 1100, '+351', false, false, now(), now()),
  (2207, 'Royaume-Uni',                     'GB', 1103, '+44',  false, false, now(), now()),
  (2208, 'Pays-Bas',                        'NL', 1100, '+31',  false, false, now(), now()),
  (2209, 'Luxembourg',                       'LU', 1100, '+352', false, false, now(), now()),
  (2210, 'Suède',                            'SE', 1167, '+46',  false, false, now(), now()),
  (2211, 'Norvège',                         'NO', 1166, '+47',  false, false, now(), now()),
  (2212, 'Danemark',                         'DK', 1168, '+45',  false, false, now(), now()),
  (2213, 'Pologne',                          'PL', 1169, '+48',  false, false, now(), now()),
  (2214, 'Turquie',                          'TR', 1156, '+90',  false, false, now(), now()),
  (2215, 'Ukraine',                          'UA', 1170, '+380', false, false, now(), now()),
  (2216, 'Russie',                           'RU', 1157, '+7',   false, false, now(), now()),
-- Americas
  (2300, 'États-Unis',                      'US', 1101, '+1',   false, false, now(), now()),
  (2301, 'Canada',                           'CA', 1146, '+1',   false, false, now(), now()),
  (2302, 'Mexique',                          'MX', 1149, '+52',  false, false, now(), now()),
  (2303, 'Brésil',                          'BR', 1145, '+55',  false, false, now(), now()),
  (2304, 'Argentine',                        'AR', 1150, '+54',  false, false, now(), now()),
  (2305, 'Colombie',                         'CO', 1152, '+57',  false, false, now(), now()),
  (2306, 'Chili',                            'CL', 1151, '+56',  false, false, now(), now()),
  (2307, 'Pérou',                           'PE', 1153, '+51',  false, false, now(), now()),
  (2308, 'Haïti',                           'HT', 1184, '+509', false, false, now(), now()),
-- Asia / Middle East / Oceania
  (2400, 'Chine',                            'CN', 1143, '+86',  false, false, now(), now()),
  (2401, 'Japon',                            'JP', 1142, '+81',  false, false, now(), now()),
  (2402, 'Corée du Sud',                    'KR', 1158, '+82',  false, false, now(), now()),
  (2403, 'Inde',                             'IN', 1144, '+91',  false, false, now(), now()),
  (2404, 'Arabie Saoudite',                 'SA', 1154, '+966', false, false, now(), now()),
  (2405, 'Émirats Arabes Unis',            'AE', 1155, '+971', false, false, now(), now()),
  (2406, 'Qatar',                            'QA', 1172, '+974', false, false, now(), now()),
  (2407, 'Koweït',                          'KW', 1173, '+965', false, false, now(), now()),
  (2408, 'Bahreïn',                        'BH', 1174, '+973', false, false, now(), now()),
  (2409, 'Liban',                            'LB', 1177, '+961', false, false, now(), now()),
  (2410, 'Singapour',                        'SG', 1159, '+65',  false, false, now(), now()),
  (2411, 'Malaisie',                         'MY', 1160, '+60',  false, false, now(), now()),
  (2412, 'Thaïlande',                       'TH', 1161, '+66',  false, false, now(), now()),
  (2413, 'Vietnam',                          'VN', 1162, '+84',  false, false, now(), now()),
  (2414, 'Indonésie',                       'ID', 1163, '+62',  false, false, now(), now()),
  (2415, 'Philippines',                      'PH', 1182, '+63',  false, false, now(), now()),
  (2416, 'Australie',                        'AU', 1148, '+61',  false, false, now(), now()),
  (2417, 'Nouvelle-Zélande',               'NZ', 1183, '+64',  false, false, now(), now()),
  (2418, 'Pakistan',                         'PK', 1164, '+92',  false, false, now(), now()),
  (2419, 'Bangladesh',                       'BD', 1165, '+880', false, false, now(), now()),
  (2420, 'Israël',                          'IL', 1171, '+972', false, false, now(), now()),
  (2421, 'Jordanie',                         'JO', 1176, '+962', false, false, now(), now()),
  (2422, 'Irak',                             'IQ', 1179, '+964', false, false, now(), now()),
  (2423, 'Oman',                             'OM', 1175, '+968', false, false, now(), now())
ON CONFLICT DO NOTHING;
